#!/bin/sh

GATEWAY_SERVER_PORT=8080
BOOKS_SERVER_PORT=5001
USERS_SERVER_PORT=5000
POSTGRES_USERS=postgres://tmosto:tmosto@172.19.0.2:5432/bookapidb
POSTGRES_USER=tmosto
POSTGRES_PASSWORD=tmosto
POSTGRES_DB=bookapidb
POSTGRES_USERS_PORT=5432
POSTGRES_CONTAINER_IP=172.19.0.2
NETWORK=postgres
GOPATH=$HOME/go
PATH=$PATH:/usr/local/go/bin
SSECRET_KEY=mysecretkeyshh