#!/bin/sh

GATEWAY_SERVER_PORT=8080
BOOKS_SERVER_PORT=5001
USERS_SERVER_PORT=5000
SHOPS_SERVER_PORT=5002
TRANSACTIONS_SERVER_PORT=5003
REDIS_PORT=6379
BOOKAPI_POSTGRES_BOOKS=postgres://tmosto:tmosto@postgres:5432/booksdb
RABBITMQ=amqp://guest:guest@rabbitmq:5672/
POSTGRES_USER=tmosto
POSTGRES_PASSWORD=tmosto
POSTGRES_BOOKSDB=booksdb
POSTGRES_BOOKS_CONTAINER_IP=172.19.0.3
NETWORK=bookapi_library
GOPATH=$HOME/go
PATH=$PATH:/usr/local/go/bin
SECRET_KEY=mysecretkeyshh
