// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The User message to represent user data
type User struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

// The response message for the AddUser method
type UserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message for the GetUser method
type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "pb.user.User")
	proto.RegisterType((*UserResponse)(nil), "pb.user.UserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "pb.user.GetUserRequest")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x4f, 0xb3, 0x40,
	0x10, 0xc6, 0xc3, 0xfb, 0x42, 0xb7, 0x8c, 0x7f, 0x62, 0x26, 0x9a, 0x6e, 0x30, 0x26, 0x0d, 0x27,
	0xbc, 0x2c, 0x51, 0x3f, 0x81, 0x5e, 0x8c, 0x17, 0x0f, 0x18, 0x2f, 0x5e, 0x9a, 0xad, 0x8c, 0x86,
	0x04, 0x0a, 0xdd, 0xa1, 0xfa, 0x79, 0xfc, 0xa6, 0x66, 0x87, 0xd2, 0x04, 0x6f, 0xf3, 0x7b, 0x9e,
	0x81, 0x79, 0x66, 0x16, 0x60, 0xc7, 0xe4, 0x4c, 0xe7, 0xda, 0xbe, 0x45, 0xd5, 0xad, 0x8d, 0xc7,
	0xf4, 0x27, 0x80, 0xf0, 0x95, 0xc9, 0xe1, 0x02, 0x94, 0x17, 0x56, 0x55, 0xa9, 0x83, 0x65, 0x90,
	0x45, 0xc5, 0xcc, 0xe3, 0x53, 0x89, 0x57, 0x00, 0x1f, 0x95, 0xe3, 0x7e, 0xb5, 0xb1, 0x0d, 0xe9,
	0x7f, 0xcb, 0x20, 0x8b, 0x8b, 0x58, 0x94, 0x67, 0xdb, 0x10, 0x5e, 0x42, 0x5c, 0xdb, 0xd1, 0xfd,
	0x2f, 0xee, 0xdc, 0x0b, 0x62, 0x9e, 0x43, 0x44, 0x8d, 0xad, 0x6a, 0x1d, 0x8a, 0x31, 0x00, 0x26,
	0x30, 0xef, 0x2c, 0xf3, 0x77, 0xeb, 0x4a, 0x1d, 0x0d, 0x5f, 0x8c, 0x8c, 0x08, 0xa1, 0x6b, 0x6b,
	0xd2, 0x4a, 0x74, 0xa9, 0xd3, 0x0c, 0x8e, 0x7d, 0xc4, 0x82, 0xb8, 0x6b, 0x37, 0x4c, 0xa8, 0x41,
	0x35, 0xc4, 0x6c, 0x3f, 0x49, 0xa2, 0xc6, 0xc5, 0x88, 0xe9, 0x35, 0x9c, 0x3e, 0x52, 0x3f, 0x34,
	0x6f, 0x77, 0xc4, 0xfd, 0xdf, 0xb5, 0xe2, 0x71, 0xad, 0xdb, 0x2d, 0x1c, 0xf9, 0xbe, 0x17, 0x72,
	0x5f, 0xd5, 0x3b, 0x61, 0x0e, 0xea, 0xbe, 0x2c, 0xe5, 0x12, 0x27, 0x66, 0x7f, 0x1c, 0xe3, 0x31,
	0xb9, 0x98, 0xe0, 0x21, 0xc4, 0x0d, 0xa8, 0xfd, 0x28, 0x5c, 0x1c, 0x3a, 0xa6, 0xc3, 0x93, 0xe9,
	0x9f, 0x1e, 0xf0, 0xed, 0xcc, 0x98, 0xdc, 0x98, 0x5c, 0xde, 0x20, 0xf7, 0xc6, 0x7a, 0x26, 0xf5,
	0xdd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x73, 0x4c, 0x72, 0x9d, 0x01, 0x00, 0x00,
}
