version: '3'

networks:
  library:
    driver: bridge

services:
  user_postgres:
    image: users-postgres
    restart: always
    build:
      context: .
      dockerfile: users/postgres/Dockerfile
    container_name: users_postgres
    networks:
      - library
    environment:
      POSTGRES_USER: tmosto
      POSTGRES_PASSWORD: tmosto
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "usersdb", "-U", "tmosto" ]
      interval: 10s
      timeout: 5s
      retries: 3

  book_postgres:
    image: books-postgres
    restart: always
    build:
      context: .
      dockerfile: books/postgres/Dockerfile
    container_name: books_postgres
    networks:
      - library
    environment:
      POSTGRES_USER: tmosto
      POSTGRES_PASSWORD: tmosto
      POSTGRES_DB: booksdb
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "booksdb", "-U", "tmosto" ]
      interval: 10s
      timeout: 5s
      retries: 3

  users-api:
    image: userapi-im
    container_name: users
    build:
      context: .
      dockerfile: users/cmd/Dockerfile
    depends_on:
      user_postgres:
        condition: service_healthy
    networks:
      - library
    environment:
      - USERS_SERVER_PORT=5000
      - POSTGRES_USERS=postgres://tmosto:tmosto@users_postgres/usersdb
      - GOPATH=$HOME/go
      - PATH=$PATH:/usr/local/go/bin
      - SECRET_KEY=mysecretkeyshh
    ports:
      - "5000:5000"

  books-api:
    image: bookapi-im
    container_name: books
    build:
      context: .
      dockerfile: ./books/cmd/Dockerfile
    depends_on:
      book_postgres:
        condition: service_healthy
    networks:
      - library
    environment:
      - BOOKS_SERVER_PORT=5001
      - POSTGRES_BOOKS=postgres://tmosto:tmosto@books_postgres/booksdb
      - GOPATH=$HOME/go
      - PATH=$PATH:/usr/local/go/bin
      - SECRET_KEY=mysecretkeyshh
    ports:
      - "5001:5001"

volumes:
  postgres-data:
