version: '3'

networks:
  library:
    driver: bridge

volumes:
  postgres_data:

services:

  postgres:
    image: postgres
    container_name: postgres
    build:
      context: .
      dockerfile: pkg/postgres/Dockerfile
    networks:
      - library
    environment:
      POSTGRES_USER: tmosto
      POSTGRES_PASSWORD: tmosto
      POSTGRES_DB: booksdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "booksdb", "-U", "tmosto" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - library
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    networks:
      - library
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  users-api:
    image: users-im
    container_name: users
    build:
      context: .
      dockerfile: users/cmd/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - library
    environment:
      - BOOKAPI_USERS_SERVER_PORT=5000
      - BOOKAPI_POSTGRES_BOOKS=postgres://tmosto:tmosto@5432/booksdb
      - BOOKAPI_RABBITMQ=amqp://guest:guest@rabbitmq:5672/
      - GOPATH=$HOME/go
      - PATH=$PATH:/usr/local/go/bin
      - BOOKAPI_SECRET_KEY=mysecretkeyshh
    ports:
      - "5000:5000"

  books-api:
    image: books-im
    container_name: books
    build:
      context: .
      dockerfile: books/cmd/Dockerfile
    depends_on:
      - users-api
    networks:
      - library
    environment:
      - BOOKAPI_BOOKS_SERVER_PORT=5001
      - BOOKAPI_POSTGRES_BOOKS=postgres://tmosto:tmosto@postgres:5432/booksdb
      - BOOKAPI_RABBITMQ=amqp://guest:guest@rabbitmq:5672/
      - GOPATH=$HOME/go
      - PATH=$PATH:/usr/local/go/bin
      - SECRET_KEY=mysecretkeyshh
    ports:
      - "5001:5001"

  shops-api:
    image: shops-im
    container_name: shops
    build:
      context: .
      dockerfile: ./shops/cmd/Dockerfile
    depends_on:
      - users-api
      - books-api
    networks:
      - library
    environment:
      - BOOKAPI_SHOPS_SERVER_PORT=5002
      - BOOKAPI_POSTGRES_BOOKS=postgres://tmosto:tmosto@postgres:5432/booksdb
      - GOPATH=$HOME/go
      - PATH=$PATH:/usr/local/go/bin
      - SECRET_KEY=mysecretkeyshh
    ports:
      - "5002:5002"

  transactions-api:
    image: transactions-im
    container_name: transactions
    build:
      context: .
      dockerfile: ./transactions/cmd/Dockerfile
    depends_on:
      - users-api
      - books-api
    networks:
      - library
    environment:
      - BOOKAPI_TRANSACTIONS_SERVER_PORT=5003
      - BOOKAPI_POSTGRES_BOOKS=postgres://tmosto:tmosto@postgres:5432/booksdb
      - BOOKAPI_RABBITMQ=amqp://guest:guest@rabbitmq:5672/
      - GOPATH=$HOME/go
      - PATH=$PATH:/usr/local/go/bin
      - SECRET_KEY=mysecretkeyshh
    ports:
      - "5003:5003"
