apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: tmosto/booksapi-go:gateway
          ports:
            - containerPort: 8080
          env:
            - name: BOOKAPI_USERS_SERVER_PORT
              value: "5000"
            - name: BOOKAPI_BOOKS_SERVER_PORT
              value: "5001"
            - name: BOOKAPI_SHOPS_SERVER_PORT
              value: "5002"
            - name: BOOKAPI_TRANSACTIONS_SERVER_PORT
              value: "5003"
            - name: BOOKAPI_GATEWAY_SERVER_PORT
              value: "8080"
