apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: tmosto/booksapi-go:userss
          ports:
            - containerPort: 5000
          env:
            - name: BOOKAPI_USERS_SERVER_PORT
              value: "5000"
            - name: BOOKAPI_POSTGRES_BOOKS
              value: postgres://tmosto:tmosto@10.97.136.53:5432/booksdb
            - name: BOOKAPI_RABBITMQ
              value: amqp://guest:guest@10.99.15.44:5672/
            - name: BOOKAPI_SECRET_KEY
              value: mysecretkeyshh
            - name: PGSSLMODE
              value: disable
