CREATE USER IF NOT EXISTS tmosto WITH PASSWORD 'tmosto' CREATEDB LOGIN;
CREATE DATABASE IF NOT EXISTS usersdb WITH OWNER = tmosto;

\c usersdb

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(200) NOT NULL,
  role VARCHAR(20),
  UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS authors (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
);

CREATE TABLE IF NOT EXISTS books (
  id SERIAL PRIMARY KEY,
  book_name VARCHAR(100) NOT NULL,
  date_published DATE,
  isbn VARCHAR(20),
  page_count INTEGER,
  user_id INTEGER REFERENCES users (id),
  author_id INTEGER REFERENCES authors (id)
);

ALTER TABLE users OWNER TO tmosto;
ALTER TABLE authors OWNER TO tmosto;
ALTER TABLE books OWNER TO tmosto;