// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBookRequest struct {
	BookId               int32    `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type BookResponse struct {
	BookId               int32    `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DatePublished        string   `protobuf:"bytes,3,opt,name=date_published,json=datePublished,proto3" json:"date_published,omitempty"`
	Isbn                 string   `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	PageCount            string   `protobuf:"bytes,5,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	UserId               int32    `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthorId             string   `protobuf:"bytes,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookResponse) Reset()         { *m = BookResponse{} }
func (m *BookResponse) String() string { return proto.CompactTextString(m) }
func (*BookResponse) ProtoMessage()    {}
func (*BookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *BookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookResponse.Unmarshal(m, b)
}
func (m *BookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookResponse.Marshal(b, m, deterministic)
}
func (m *BookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookResponse.Merge(m, src)
}
func (m *BookResponse) XXX_Size() int {
	return xxx_messageInfo_BookResponse.Size(m)
}
func (m *BookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookResponse proto.InternalMessageInfo

func (m *BookResponse) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *BookResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BookResponse) GetDatePublished() string {
	if m != nil {
		return m.DatePublished
	}
	return ""
}

func (m *BookResponse) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *BookResponse) GetPageCount() string {
	if m != nil {
		return m.PageCount
	}
	return ""
}

func (m *BookResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BookResponse) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetBookRequest)(nil), "book.GetBookRequest")
	proto.RegisterType((*BookResponse)(nil), "book.BookResponse")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xad, 0x76, 0x5b, 0x3b, 0xea, 0x22, 0x83, 0x60, 0x51, 0x84, 0xa5, 0x20, 0xac, 0x97,
	0x14, 0x14, 0xff, 0xc0, 0x2a, 0x48, 0x6f, 0x52, 0x6f, 0x5e, 0x4a, 0xbb, 0x19, 0xdc, 0xb2, 0xda,
	0xa9, 0x4d, 0xe2, 0x9f, 0xf4, 0x4f, 0xc9, 0x24, 0x0a, 0x7a, 0xf0, 0xf6, 0xf2, 0xbd, 0x79, 0xf0,
	0xf2, 0x00, 0x3a, 0xe6, 0xad, 0x1a, 0x27, 0xb6, 0x8c, 0xb1, 0xe8, 0xe2, 0x0a, 0xe6, 0x0f, 0x64,
	0x57, 0xcc, 0xdb, 0x9a, 0xde, 0x1d, 0x19, 0x8b, 0xa7, 0x90, 0x8a, 0xd3, 0xf4, 0x3a, 0x8f, 0x16,
	0xd1, 0x72, 0x56, 0x27, 0xf2, 0xac, 0x74, 0xf1, 0x19, 0xc1, 0x61, 0x38, 0x34, 0x23, 0x0f, 0x86,
	0xfe, 0xbd, 0x44, 0x84, 0x78, 0x68, 0xdf, 0x28, 0xdf, 0x5d, 0x44, 0xcb, 0xac, 0xf6, 0x1a, 0x2f,
	0x61, 0xae, 0x5b, 0x4b, 0xcd, 0xe8, 0xba, 0xd7, 0xde, 0x6c, 0x48, 0xe7, 0x7b, 0xde, 0x3d, 0x12,
	0xfa, 0xf8, 0x03, 0x25, 0xda, 0x9b, 0x6e, 0xc8, 0xe3, 0x10, 0x15, 0x8d, 0x17, 0x00, 0x63, 0xfb,
	0x42, 0xcd, 0x9a, 0xdd, 0x60, 0xf3, 0x99, 0x77, 0x32, 0x21, 0x77, 0x02, 0xa4, 0x86, 0x33, 0x34,
	0x49, 0x8d, 0x24, 0xd4, 0x90, 0x67, 0xa5, 0xf1, 0x1c, 0xb2, 0xd6, 0xd9, 0x0d, 0x7b, 0x2b, 0xf5,
	0xb1, 0xfd, 0x00, 0x2a, 0x7d, 0x7d, 0x0f, 0x07, 0xf2, 0x99, 0x27, 0x9a, 0x3e, 0xfa, 0x35, 0xe1,
	0x2d, 0xa4, 0xdf, 0x3b, 0xe0, 0x89, 0xf2, 0x2b, 0xfd, 0x9d, 0xe5, 0x0c, 0x03, 0xfd, 0x3d, 0x40,
	0xb1, 0xb3, 0xc2, 0xe7, 0x63, 0xa5, 0x4a, 0xa5, 0x4a, 0xbf, 0x69, 0x29, 0x27, 0x5d, 0xe2, 0xf5,
	0xcd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0xa4, 0xc0, 0x7f, 0x6d, 0x01, 0x00, 0x00,
}
